### ISSUE TITLE
Wrong loading of dig_H5

### ISSUE THREAD

**Issue by ojschumann** [rm-hull/bme280#11]
Hi, 

I encountered a bug when comparing this lib with an implementation on my arduino. I get different values of the dig_H5 parameter. After checking the source and the specs, I found that in the loading of the dig_H5 the nibble from e5 is masked in the wrong way:

```python
compensation_params.dig_H5 = ((e5 >> 4) & 0xF0) | (e6 << 4)
```

The mask has to be changed from 0xF0 to 0x0F (or the shifting interchanged)

```python
compensation_params.dig_H5 = ((e5 >> 4) & 0x0F) | (e6 << 4)
```

Best,
  Olaf

**Comment by rm-hull** [comment]
You'll see that this was was reported in #2, and updated in https://github.com/rm-hull/bme280/commit/76f4e0c8a002d42e619ede17edb5da7dce88bdc2, but re-looking at this again, I believe you are correct!

**Comment by rm-hull** [comment]
version 0.2.2 released with this change applied.
thanks for taking the time to report the problem
