### ISSUE TITLE
'load_calibration_params' problem when running script

### ISSUE THREAD

**Issue by bigdestroyer** [rm-hull/bme280#12]
`Traceback (most recent call last):
  File "sensor.py", line 8, in <module>
    calibration_params = bme280.load_calibration_params(bus, address)
AttributeError: 'module' object has no attribute 'load_calibration_params'
`
This is the problem I get when running my script for my weather station. It is a python script but for the sake to get it uploaded with github's limited file extensions I made it a text file
[bme280_sensor.txt](https://github.com/rm-hull/bme280/files/2793708/bme280_sensor.txt)

**Comment by rm-hull** [comment]
What is the output when you run `pip list | grep -i bme` on the command line?

**Comment by bigdestroyer** [comment]
This is what I get with the above command
```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
bme280 (0.5)
RPi.bme280 (0.2.2)
```

**Comment by bigdestroyer** [comment]
Any updates on the issue?

**Comment by rm-hull** [comment]
Sounds like you need to uninstall the bme280 library and reinstall rpi.bme280

**Comment by bigdestroyer** [comment]
Thanks, I will give it a try and let you know the outcome.

**Comment by rm-hull** [comment]
Any news?

**Comment by bigdestroyer** [comment]
Could not get the time yet to try it out maybe this weekend. Will let you
know as soon as I get the chance to do it

Ryan Sylvester

**Comment by tomiisp** [comment]
I have the same problem but I have only RPi.bme280 installed, any hint ?

```
Traceback (most recent call last):
  File "bme280.py", line 2, in <module>
    import bme280
  File "/home/snmp/bme280.py", line 8, in <module>
    calibration_params = bme280.load_calibration_params(bus, address)
AttributeError: 'module' object has no attribute 'load_calibration_params'
```

**Comment by tomiisp** [comment]
Ok, my bad... test file was named "bme280.py" and this was a problem, just renaming file to "bme280test.py" fix this problem

**Comment by skibum-za** [comment]
Funny I have the same issue. Although it's not related to my naming of my python script as I'm using the 'sample.py' supplied. 

If I attempt to run the 'sample.py' script from the directory /home/pi/bme280/examples it fails with the error :- 

` python sample.py`
`Traceback (most recent call last):`
`  File "sample.py", line 13, in <module>`
`    calibration_params = bme280.load_calibration_params(bus, address)`
`AttributeError: 'module' object has no attribute 'load_calibration_params'`

however, if I copy the code to the directory /home/pi/bme280 it works fine :- 

`python sample.py`
`compensation_params = {'dig_H1': 75, 'dig_H3': 0, 'dig_H2': 386, 'dig_H5': 50, 'dig_H4': 264, 'dig_H6': '30, 'dig_P9': 4285, 'dig_P8': -10230, 'dig_T1': 28383, 'dig_T3': 50, 'dig_T2': 26590, 'dig_P1': 35048, 'dig_P3': 3024, 'dig_P2': -10521, 'dig_P5': 15, 'dig_P4': 6438, 'dig_P7': 9900, 'dig_P6': -7}`
`uncompensated_reading(temp=0x0007F3A0, pressure=0x0005EBD0, humidity=0x00005F53, block=5E:BD:00:7F:3A:00:5F:53)`
`compensated_reading(id=a7d93be9-635b-4f26-b4e3-5d733c21db29, timestamp=2019-12-22 15:21:27.399743UTC, temp=21.238 °C, pressure=987.47 hPa, humidity=43.98 % rH)`

Trying to run the code outside of the bme280 directory fails for me completely.

It seems to me that you need the a directory called 'bme280' in your current directory with the files "const.py  const.pyc  __init__.py  __init__.pyc  reader.py  reader.pyc" in it. 

I competely uninstalled and just installed it from pip. The it doesn't work at all as no where do you have the files it seems to require. Seems something is missing during the install.

**Comment by Unixware** [comment]
> Funny I have the same issue. Although it's not related to my naming of my python script as I'm using the 'sample.py' supplied.
> 
> If I attempt to run the 'sample.py' script from the directory /home/pi/bme280/examples it fails with the error :-
> 
> ` python sample.py`
> `Traceback (most recent call last):`
> ` File "sample.py", line 13, in <module>`
> ` calibration_params = bme280.load_calibration_params(bus, address)`
> `AttributeError: 'module' object has no attribute 'load_calibration_params'`
> 
> however, if I copy the code to the directory /home/pi/bme280 it works fine :-
> 
> `python sample.py`
> `compensation_params = {'dig_H1': 75, 'dig_H3': 0, 'dig_H2': 386, 'dig_H5': 50, 'dig_H4': 264, 'dig_H6': '30, 'dig_P9': 4285, 'dig_P8': -10230, 'dig_T1': 28383, 'dig_T3': 50, 'dig_T2': 26590, 'dig_P1': 35048, 'dig_P3': 3024, 'dig_P2': -10521, 'dig_P5': 15, 'dig_P4': 6438, 'dig_P7': 9900, 'dig_P6': -7}`
> `uncompensated_reading(temp=0x0007F3A0, pressure=0x0005EBD0, humidity=0x00005F53, block=5E:BD:00:7F:3A:00:5F:53)`
> `compensated_reading(id=a7d93be9-635b-4f26-b4e3-5d733c21db29, timestamp=2019-12-22 15:21:27.399743UTC, temp=21.238 °C, pressure=987.47 hPa, humidity=43.98 % rH)`
> 
> Trying to run the code outside of the bme280 directory fails for me completely.
> 
> It seems to me that you need the a directory called 'bme280' in your current directory with the files "const.py const.pyc **init**.py **init**.pyc reader.py reader.pyc" in it.
> 
> I competely uninstalled and just installed it from pip. The it doesn't work at all as no where do you have the files it seems to require. Seems something is missing during the install.

seriously what kind of crap is that? I am getting the same error as OP , I will try your solution to see is this script works..

**Comment by m4nzm333** [comment]
> Funny I have the same issue. Although it's not related to my naming of my python script as I'm using the 'sample.py' supplied.
> 
> If I attempt to run the 'sample.py' script from the directory /home/pi/bme280/examples it fails with the error :-
> 
> ` python sample.py`
> `Traceback (most recent call last):`
> ` File "sample.py", line 13, in <module>`
> ` calibration_params = bme280.load_calibration_params(bus, address)`
> `AttributeError: 'module' object has no attribute 'load_calibration_params'`
> 
> however, if I copy the code to the directory /home/pi/bme280 it works fine :-
> 
> `python sample.py`
> `compensation_params = {'dig_H1': 75, 'dig_H3': 0, 'dig_H2': 386, 'dig_H5': 50, 'dig_H4': 264, 'dig_H6': '30, 'dig_P9': 4285, 'dig_P8': -10230, 'dig_T1': 28383, 'dig_T3': 50, 'dig_T2': 26590, 'dig_P1': 35048, 'dig_P3': 3024, 'dig_P2': -10521, 'dig_P5': 15, 'dig_P4': 6438, 'dig_P7': 9900, 'dig_P6': -7}`
> `uncompensated_reading(temp=0x0007F3A0, pressure=0x0005EBD0, humidity=0x00005F53, block=5E:BD:00:7F:3A:00:5F:53)`
> `compensated_reading(id=a7d93be9-635b-4f26-b4e3-5d733c21db29, timestamp=2019-12-22 15:21:27.399743UTC, temp=21.238 °C, pressure=987.47 hPa, humidity=43.98 % rH)`
> 
> Trying to run the code outside of the bme280 directory fails for me completely.
> 
> It seems to me that you need the a directory called 'bme280' in your current directory with the files "const.py const.pyc **init**.py **init**.pyc reader.py reader.pyc" in it.
> 
> I competely uninstalled and just installed it from pip. The it doesn't work at all as no where do you have the files it seems to require. Seems something is missing during the install.

Thank you, for your solution.
It works. But, how to run the script from the outside of the directory?

**Comment by boris-so** [comment]
I am not very familiar with python, but believe there is name conflict between this package (RPi.bme280) and another one, called bme280. Both have modules named "bme280".
I had both of them installed and had same issue. Try to delete both and reinstall RPi.bme280. That worked for me. Also now i can run my script from any directory and it works.

**Comment by alpalii** [comment]
> I am not very familiar with python, but believe there is name conflict between this package (RPi.bme280) and another one, called bme280. Both have modules named "bme280".
> I had both of them installed and had same issue. Try to delete both and reinstall RPi.bme280. That worked for me. Also now i can run my script from any directory and it works.

How can I remove RPi.bme280 and bme280? I am trying with sudo apt-get --purge remove <RPi.bme280> but it doesn't works.

**Comment by m4nzm333** [comment]
> > I am not very familiar with python, but believe there is name conflict between this package (RPi.bme280) and another one, called bme280. Both have modules named "bme280".
> > I had both of them installed and had same issue. Try to delete both and reinstall RPi.bme280. That worked for me. Also now i can run my script from any directory and it works.
> 
> How can I remove RPi.bme280 and bme280? I am trying with sudo apt-get --purge remove <RPi.bme280> but it doesn't works.

You should use 
`pip3 uninstall bme280` or `pip uninstall bme280`

**Comment by alpalii** [comment]
> You should use
> `pip3 uninstall bme280` or `pip uninstall bme280`

Thank you for your quick answer!

**Comment by alpalii** [comment]
I have uninstalled both bme280 and RPi.bme280 and reinstalled the second one, but I only get .txt files when installing RPi.bme280, I supossed it was expected to give a .py file with the code. It gives the same attribute error when running the program for the bme280 sensor. Does anyone know what should I get when doing "sudo pip install RPi.bme280"?

**Comment by boris-so** [comment]
> Does anyone know what should I get when doing "sudo pip install RPi.bme280"?

You can find location for a python package with `pip show RPi.bme280` if the package installed already.
For me it shows:
```
$ pip3 show RPi.bme280
Name: RPi.bme280
Version: 0.2.3
Summary: A library to drive a Bosch BME280 temperature, humidity, pressure sensor over I2C
Home-page: https://github.com/rm-hull/bme280
Author: Richard Hull
Author-email: richard.hull@destructuring-bind.org
License: MIT
Location: /home/boris/.local/lib/python3.7/site-packages
Requires: smbus2
Required-by: 
```

Two notions may be important at the moment:
1. `pip` and `pip3` are different for python versions 2 and 3. I suggest you should use `pip3`
2. I bielieve the `sudo` is unnecessary here for package installation. Packages should be installed into your user`s home location to be discovered when imported in script.

Then take a look into the file:
```
$ cat ~/.local/lib/python3.7/site-packages/RPi.bme280-0.2.3.dist-info/RECORD 
RPi.bme280-0.2.3.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
RPi.bme280-0.2.3.dist-info/LICENSE.rst,sha256=-gH_h4n_d6h1BlWvRB80q5AZDIpnyyZOxH5q3bD5wyg,1081
RPi.bme280-0.2.3.dist-info/METADATA,sha256=CdHuDhiUSdr3WZiQOebvdA_7VunRMQGjyEmXp9p-_Qs,7977
RPi.bme280-0.2.3.dist-info/RECORD,,
RPi.bme280-0.2.3.dist-info/WHEEL,sha256=CihQvCnsGZQBGAHLEUMf0IdA4fRduS_NBUTMgCTtvPM,110
RPi.bme280-0.2.3.dist-info/top_level.txt,sha256=akOWEt2_vXS0A30sKz_7dK2a9D0myQsD5EnnXQuL5SU,7
bme280/__init__.py,sha256=gUyS7D2h8-vK-40QePKiP1nEFBb0mwA2JqHms2_paSs,8317
bme280/__pycache__/__init__.cpython-37.pyc,,
bme280/__pycache__/const.cpython-37.pyc,,
bme280/__pycache__/reader.cpython-37.pyc,,
bme280/const.py,sha256=rdtvBiVropTbphcdzPY-9nezuZvG5sEh9si9H__b4NY,1699
bme280/reader.py,sha256=7SkZpDpkmh6P4Q5l_LR8wAjCy9xoEcht7aWUrBOMWxA,1971
```
It shows pyc-files located at bme280 dir located at `~/.local/lib/python3.7/site-packages/`. The code to be imported is contained there.

So, after all verified you should be able to import 'bme280' module in pytohn3

**Comment by alpalii** [comment]
> > Does anyone know what should I get when doing "sudo pip install RPi.bme280"?
> 
> You can find location for a python package with `pip show RPi.bme280` if the package installed already.
> For me it shows:
> 
> ```
> $ pip3 show RPi.bme280
> Name: RPi.bme280
> Version: 0.2.3
> Summary: A library to drive a Bosch BME280 temperature, humidity, pressure sensor over I2C
> Home-page: https://github.com/rm-hull/bme280
> Author: Richard Hull
> Author-email: richard.hull@destructuring-bind.org
> License: MIT
> Location: /home/boris/.local/lib/python3.7/site-packages
> Requires: smbus2
> Required-by: 
> ```
> 
> Two notions may be important at the moment:
> 
> 1. `pip` and `pip3` are different for python versions 2 and 3. I suggest you should use `pip3`
> 2. I bielieve the `sudo` is unnecessary here for package installation. Packages should be installed into your user`s home location to be discovered when imported in script.
> 
> Then take a look into the file:
> 
> ```
> $ cat ~/.local/lib/python3.7/site-packages/RPi.bme280-0.2.3.dist-info/RECORD 
> RPi.bme280-0.2.3.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
> RPi.bme280-0.2.3.dist-info/LICENSE.rst,sha256=-gH_h4n_d6h1BlWvRB80q5AZDIpnyyZOxH5q3bD5wyg,1081
> RPi.bme280-0.2.3.dist-info/METADATA,sha256=CdHuDhiUSdr3WZiQOebvdA_7VunRMQGjyEmXp9p-_Qs,7977
> RPi.bme280-0.2.3.dist-info/RECORD,,
> RPi.bme280-0.2.3.dist-info/WHEEL,sha256=CihQvCnsGZQBGAHLEUMf0IdA4fRduS_NBUTMgCTtvPM,110
> RPi.bme280-0.2.3.dist-info/top_level.txt,sha256=akOWEt2_vXS0A30sKz_7dK2a9D0myQsD5EnnXQuL5SU,7
> bme280/__init__.py,sha256=gUyS7D2h8-vK-40QePKiP1nEFBb0mwA2JqHms2_paSs,8317
> bme280/__pycache__/__init__.cpython-37.pyc,,
> bme280/__pycache__/const.cpython-37.pyc,,
> bme280/__pycache__/reader.cpython-37.pyc,,
> bme280/const.py,sha256=rdtvBiVropTbphcdzPY-9nezuZvG5sEh9si9H__b4NY,1699
> bme280/reader.py,sha256=7SkZpDpkmh6P4Q5l_LR8wAjCy9xoEcht7aWUrBOMWxA,1971
> ```
> 
> It shows pyc-files located at bme280 dir located at `~/.local/lib/python3.7/site-packages/`. The code to be imported is contained there.
> 
> So, after all verified you should be able to import 'bme280' module in pytohn3

Thank you very much Boris! Until today I had no time to test what you said. Now it works!

**Comment by KyanoDM** [comment]
I am so confused about this. I tried everything from the comments above, but nothing worked for me. I still get this error:   _File "/home/pi/test.py", line 83, in <module>
    bme280.load_calibration_params(bus,address)
AttributeError: module 'bme280' has no attribute 'load_calibration_params'_ . I reinstalled bme280 and RPi.bme280 a couple times, changed the name and location of my program  multiple times. what am i doing wrong?

**Comment by jkalucki** [comment]
KyanoBoi, Can you post the shortest possible program that reproduces the problem? How are you importing bme280? What are you calling before load_calibration_params?

pi@pi1:~ $ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smbus2
>>> import bme280
>>> port = 1
>>> address = 0x77
>>> bus = smbus2.SMBus(port)
>>> compensation_params = bme280.load_calibration_params(bus, address)
>>> print (compensation_params)
{'dig_T1': 28328, 'dig_T2': 26357, 'dig_T3': 50, 'dig_P1': 37489, 'dig_P2': -10759, 'dig_P3': 3024, 'dig_P4': 6331, 'dig_P5': 36, 'dig_P6': -7, 'dig_P7': 12300, 'dig_P8': -12000, 'dig_P9': 5000, 'dig_H1': 75, 'dig_H2': 335, 'dig_H3': 0, 'dig_H4': 389, 'dig_H5': 50, 'dig_H6': 30}
>>>

**Comment by rm-hull** [comment]
You only need RPi.bme280, not bme280. There is likely a namespace clash that is causing the issue

**Comment by KyanoDM** [comment]
Hello, thanks for responding. 
The following code is the shortest i've tried:

import bme280
import smbus2
from time import sleep

port = 1
address = 0x76
bus = smbus2.SMBus(port)

bme280.load_calibration_params(bus,address)

while True:
	bme280_data = bme280.sample(bus, address)
	humidity = bme280_data.humidity
	pressure = bme280_data.pressure
	ambient_temperature = bme280_data.temperature
	print(humidity, pressure, ambient_temperature)
	sleep(1)

error: 
Traceback (most recent call last):
File "/home/pi/dsqdqs.py", line 9, in <module>
bme280.load_calibration_params(bus,address)
AttributeError: module 'bme280' has no attribute 'load_calibration_params'

I tried to import RPi.bme280, but it just said: No module named 'RPi.bme280'.

Thanks for trying to help, by the way. This is my project for school and I'm panicking a little bit because it has to be completed in a month and a half, and I've got a lot of work still. The sudden errors give me stress. I hope we can fix this ASAP. Thanks.

**Comment by jkalucki** [comment]
Seems like something is installed incorrectly, or as the other responder said, a namespace collision. See that the expected versions are loading. Perhaps reinstall/upgrade python and the libraries to the latest.

$ pip3 list | egrep bme280\|smbus2
RPi.bme280          0.2.4
smbus2              0.4.2
$ pip3 show smbus2 RPi.bme280
Name: smbus2
Version: 0.4.2
Summary: smbus2 is a drop-in replacement for smbus-cffi/smbus-python in pure Python
Home-page: https://github.com/kplindegaard/smbus2
Author: Karl-Petter Lindegaard
Author-email: kp.lindegaard@gmail.com
License: MIT
Location: /usr/local/lib/python3.9/dist-packages
Requires: 
Required-by: RPi.bme280
---
Name: RPi.bme280
Version: 0.2.4
Summary: A library to drive a Bosch BME280 temperature, humidity, pressure sensor over I2C
Home-page: https://github.com/rm-hull/bme280
Author: Richard Hull
Author-email: richard.hull@destructuring-bind.org
License: MIT
Location: /usr/local/lib/python3.9/dist-packages
Requires: smbus2, pytz
Required-by: 
$ pip3 show pytz
Name: pytz
Version: 2022.6
Summary: World timezone definitions, modern and historical
Home-page: http://pythonhosted.org/pytz
Author: Stuart Bishop
Author-email: stuart@stuartbishop.net
License: MIT
Location: /usr/local/lib/python3.9/dist-packages
Requires: 
Required-by: RPi.bme280, pandas
$ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smbus2
im>>> import bme280
>>> print  (smbus2.__version__)
0.4.2
>>> print (bme280.__version__)
0.2.4
>>>

**Comment by KyanoDM** [comment]
> Seems like something is installed incorrectly, or as the other responder said, a namespace collision. See that the expected versions are loading. Perhaps reinstall/upgrade python and the libraries to the latest.
> 
> ## $ pip3 list | egrep bme280|smbus2
> RPi.bme280 0.2.4
> smbus2 0.4.2
> $ pip3 show smbus2 RPi.bme280
> Name: smbus2
> Version: 0.4.2
> Summary: smbus2 is a drop-in replacement for smbus-cffi/smbus-python in pure Python
> Home-page: https://github.com/kplindegaard/smbus2
> Author: Karl-Petter Lindegaard
> Author-email: [kp.lindegaard@gmail.com](mailto:kp.lindegaard@gmail.com)
> License: MIT
> Location: /usr/local/lib/python3.9/dist-packages
> Requires:
> Required-by: RPi.bme280
> Name: RPi.bme280 Version: 0.2.4 Summary: A library to drive a Bosch BME280 temperature, humidity, pressure sensor over I2C Home-page: https://github.com/rm-hull/bme280 Author: Richard Hull Author-email: [richard.hull@destructuring-bind.org](mailto:richard.hull@destructuring-bind.org) License: MIT Location: /usr/local/lib/python3.9/dist-packages Requires: smbus2, pytz Required-by: $ pip3 show pytz Name: pytz Version: 2022.6 Summary: World timezone definitions, modern and historical Home-page: http://pythonhosted.org/pytz Author: Stuart Bishop Author-email: [stuart@stuartbishop.net](mailto:stuart@stuartbishop.net) License: MIT Location: /usr/local/lib/python3.9/dist-packages Requires: Required-by: RPi.bme280, pandas $ python3 Python 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import smbus2
> > > > im>>> import bme280
> > > > print  (smbus2.**version**)
> > > > 0.4.2
> > > > print (bme280.**version**)
> > > > 0.2.4

So i updated everything to the latest version, this changed nothing. i also tried to run the program in a myenv, i think this is like a vertual machine of some sort, this gave this error: 
AttributeError: module 'bme280' has no attribute 'BME280'
i also used other code: 
import smbus2
import bme280

# set up the I2C bus
bus = smbus2.SMBus(1)

# set up the BME280 sensor
bme280_sensor = bme280.BME280(i2c_dev=bus)

# read the temperature, pressure, and humidity
temperature, pressure, humidity = bme280_sensor.get_temperature_pressure_humidity()

# print the results
print(f"Temperature: {temperature:.2f} C")
print(f"Pressure: {pressure:.2f} hPa")
print(f"Humidity: {humidity:.2f} %")

I am stuck. I have no idea what i can do. If someone would like to join a voice call, or if you have  a other idea what could be wrong you can always reply. Thanks

**Comment by KyanoDM** [comment]
I'm just gonne use a diffrint library. the following code works for me: 

import time
import board
import adafruit_bme280.advanced as adafruit_bme280

i2c = board.I2C()
bme280 = adafruit_bme280.Adafruit_BME280_I2C(i2c)

bme280.sea_level_pressure = 1013.25
bme280.mode = adafruit_bme280.MODE_NORMAL
bme280.standby_period = adafruit_bme280.STANDBY_TC_500
bme280.iir_filter = adafruit_bme280.IIR_FILTER_X16
bme280.overscan_pressure = adafruit_bme280.OVERSCAN_X16
bme280.overscan_humidity = adafruit_bme280.OVERSCAN_X1
bme280.overscan_temperature = adafruit_bme280.OVERSCAN_X2
time.sleep(1)

while True:
    print("\nTemperature: %0.1f C" % bme280.temperature)
    print("Humidity: %0.1f %%" % bme280.relative_humidity)
    print("Pressure: %0.1f hPa" % bme280.pressure)
    print("Altitude = %0.2f meters" % bme280.altitude)
    time.sleep(2)

**Comment by M66B** [comment]
If you installed *bme280* and later *RPi.bme280*, uninstall both, delete the folder *\_\_pycache\_\_* and install *RPi.bme280* again.
