### ISSUE TITLE
Two sensors with 0x76 address can not be read

### ISSUE THREAD

**Issue by tomtactom** [rm-hull/bme280#16]
Hi there,
I have several sensors, but they all have the same address.
I used an extra cable for the GND. I connected SCL to the same cable. Either I don't get any value or I get -142.11129819307826 as the temperature. Then when I unplug a sensor it returns to 22.124424953595735 as the normal temperature.
$ i2cdetect -y 1
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- 76 --
```

Is there a way to change the address from **0x76** to **0x77**?

**Comment by rm-hull** [comment]
You should be able to change the address of one of them by either soldering over (and joining) two of the the three address-select pads on the breakout board. Refer back to where you got it from to see if there is a section about setting the address. If successful one would be 0x76, the other 0x77

That should be equivalent to what they are talking about here: https://www.raspberrypi.org/forums/viewtopic.php?t=161628

**Comment by tomtactom** [comment]
The problem is that my sensor doesn't have an SDO connector.
https://www.amazon.de/dp/B07FS95JXT

> The (SPI) SDO line needs to be strapped to ground for I2C address 0x76 and 3V3 for address 0x77.
> I guess it has been left floating.

I don't have this SDO input

**Comment by rm-hull** [comment]
Solder two of the three pads next to the IC ... that sets the address ... that is the SDO line 
![](https://images-na.ssl-images-amazon.com/images/I/71TQcxuAOEL._SX522_.jpg)

**Comment by tomtactom** [comment]
I don't really understand what you mean by _IC_. What exactly do I have to solder now?
Do you mean these little things? https://i.ibb.co/wwZZ1QP/a.jpg
Or what is meant is that I have to fill with solder the large hole at the top right?
Sorry, I'm still new to the hardware area. 😅

**Comment by rm-hull** [comment]
> Do you mean these little things? https://i.ibb.co/wwZZ1QP/a.jpg 

Yes, you need to bridge two of the pads with a blob of solder. The middle one will be the SDO line while the others will be ground and power. By soldering across from say, the left pad to the middle pad might tie SDO low and would set the address as 0x76. Else if you soldered across the middle pad to the right pad, this might tie the SDO line high and set the address to 0x77. 

I don’t know for sure which way round the pads/addresses are, but hopefully this gives you an rough idea.

IC = integrated circuit = the little square metal package on the circuit board
