### ISSUE TITLE
Hasn't been updated to use LUMA.OLED

### ISSUE THREAD

**Issue by sheridat** [rm-hull/bme280#5]
Any chance of updating the weatherstation example used in this project to use LUMA.CORE and LUMA.OLED?

**Comment by rm-hull** [comment]
Yes will do - hadn't spotted that

**Comment by rm-hull** [comment]
Just pushed a new commit into master - see f13d933 - I haven't tested this but it _should_ be ok... 

Let me know if it works/doesn't work.

**Comment by sheridat** [comment]
Works great - i did have to modify to use my BME280's address which is Ox77, Just copied the relevant lines from examples/sample.py. 
Off now to look at your weatherstation and lua.garden repos
Thank You for amending it so quickly

**Comment by rm-hull** [comment]
Great stuff. I'm aware that some BME280 are on 0x76, others on 0x77 ... I've updated the example with a comment or two.

The weatherstation has been chugging away for a good few months now and has accrued over 500K samples. The lua-garden does the same thing but using an ESP8266, a LiPo cell and solar charger (and is a work-in-progress), and once stable will be deployed in the garden. I'll update with some block diagrams and wiring details soon.

**Comment by sheridat** [comment]
Really looking forward to copying the lua.garden once your happy with it.
