### ISSUE TITLE
bme280 not working with more than one sensor?

### ISSUE THREAD

**Issue by Robaquez** [rm-hull/bme280#6]
I apologize in advance if I am missing something obvious, I am reasonably fluent in C/C++, but know next to nothing about Python.

Is there a way to use the module with more than one sensor? I have two at 0x76 and 0x77, I can read them separately, but load_calibration_params() can be called only once, second call generates an error:

```
Traceback (most recent call last):
  File "bme280trials.py", line 23, in <module>
    bme280.load_calibration_params(bus, address)
  File "/usr/local/lib/python2.7/dist-packages/RPi.bme280-0.1.3-py2.7.egg/bme280/__init__.py", line 138, in load_calibration_params
    compensation_params.dig_T1 = read.unsigned_short(0x88)
  File "/usr/local/lib/python2.7/dist-packages/RPi.bme280-0.1.3-py2.7.egg/bme280/const.py", line 37, in __setattr__
    raise self.ConstError("Can't rebind const(%s)" % name)
bme280.const.ConstError: Can't rebind const(dig_T1)
```

That unfortunately means that second sensor readings can't be corrected.

**Comment by rm-hull** [comment]
Yes, that sounds like something that would be useful. I will have a look changing the implementation to support that.

**Comment by Tom-3112** [comment]
I would appreciate this enhancement as well as without calibration the humidity difference is about 10% with my two BME280 sensors. 

Sensor1: temp=23.263 °C, pressure=931.65 hPa, humidity=36.29 % rH
vs.
Sensor2: temp=21.333 °C, pressure=1018.75 hPa, humidity=45.65 % rH

**Comment by rm-hull** [comment]
@Robaquez @Tom-3112: I have a commit which will fix this, but I would like to add some tests as well. 

Could you post the output of

```python
import smbus2
import bme280

port = 1
address = 0x76  # 0x77
bus = smbus2.SMBus(port)

bme280.load_calibration_params(bus, address)
print(calibration_params)
```

for both devices please

**Comment by rm-hull** [comment]
0.2.0 released with a fix in for this; please see the README example for how to supply different compensation parameters

**Comment by Robaquez** [comment]
Richard napisal(a):

(...)
RH> bme280.load_calibration_params(bus, address)
RH> print(calibration_params)

NameError: name 'calibration_params' is not defined

But once I replaced the next to last line with

calibration_params = bme280.load_calibration_params(bus, address)

I got

borek@raspberrypi ~/python $ python bme_test.py
{'dig_H1': 75, 'dig_H3': 0, 'dig_H2': 366, 'dig_H5': 48, 'dig_H4': 309, 'dig_H6': 30, 'dig_P9': 4285, 'dig_P8': -10230, 'dig_T1': 28181, 'dig_T3': 50, 'dig_T2': 26489, 'dig_P1': 37786, 'dig_P3': 3024, 'dig_P2': -10801, 'dig_P5': -47, 'dig_P4': 6915, 'dig_P7': 9900, 'dig_P6': -7}
borek@raspberrypi ~/python $ vim bme_test.py
borek@raspberrypi ~/python $ python bme_test.py
{'dig_H1': 75, 'dig_H3': 0, 'dig_H2': 364, 'dig_H5': 48, 'dig_H4': 314, 'dig_H6': 30, 'dig_P9': 4285, 'dig_P8': -10230, 'dig_T1': 28357, 'dig_T3': 50, 'dig_T2': 26376, 'dig_P1': 37590, 'dig_P3': 3024, 'dig_P2': -10798, 'dig_P5': -69, 'dig_P4': 7748, 'dig_P7': 9900, 'dig_P6': -7}

So it definitely reads different params from different addresses.

Haven't tested it with my code yet. I didn't want to wait after
reporting the issue so I made a quick and dirty modification of the
library. That allowed me to create two separate bme280 objects each
having its own calibration parameters, something like:

sensor_out = bme280(bus,0x76)
sensor_in = bme280(bus,0x77)
sensor_out.load_calibration_params()
sensor_in.load_calibration_params()

As my code works and logs data every minute I am a bit reluctant to
change it now, but will probably try later.

Z poważaniem
Marcin Borkowski
-- 
BPP Marcin Borkowski, ul. Architektów 14, 05-270 Marki, Poland
http://www.chembuddy.com, http://www.bpp.com.pl

**Comment by Robaquez** [comment]
One additional comment - it works, but I find passing both address and
the calibration parameters each time a bit awkward and excessive, I
feel like they should be automatically connected in some way:

import smbus2
import bme280

port = 1
bus = smbus2.SMBus(port)
calibration_params_0x76 = bme280.load_calibration_params(bus, 0x76)
calibration_params_0x77 = bme280.load_calibration_params(bus, 0x77)

# here: one parameters should be enough
data = bme280.sample(bus, 0x76, calibration_params_0x76)
print(data)

data = bme280.sample(bus, 0x77, calibration_params_0x77)
print(data)

Z poważaniem
Marcin Borkowski
-- 
BPP Marcin Borkowski, ul. Architektów 14, 05-270 Marki, Poland
http://www.chembuddy.com, http://www.bpp.com.pl

**Comment by rm-hull** [comment]
You can actually omit the `calibration_params` altogether, and it will recalculate them on the fly. This code below should work now, but might be inefficient if `bme280.sample(...)` is needed to be called a lot.  I think I might memoize them so that this is done once only. Standby for 0.2.1


```python

import smbus2
import bme280

port = 1
bus = smbus2.SMBus(port)

data = bme280.sample(bus, 0x76)
print(data)

data = bme280.sample(bus, 0x77)
print(data)
```

p.s. I did this so it remains compatible with code that uses 0.1.x

**Comment by rm-hull** [comment]
Ok, so 0.2.1 released with the memoization performance improvement
